### ISSUE TITLE
How to install it

### ISSUE THREAD

**Issue by rdomingue** [CubieDev/TwitchCubieBotGUI#2]
It seems pretty nice and perfectly what I was looking for. I'm new with this kind of bot. How should I install it. What should I do to implement it on my stream ?
Thanks

**Comment by tomaarsen** [comment]
I just realised that I do not get notifications for issues placed on my repositories. Which is why I did not see this issue earlier.
Luckily, you did the right thing and contacted me on discord, so we could get this sorted.

I'll take this moment to put a better installation guide on my TODO-list, and to fix my Github settings.
